### ISSUE TITLE
MMDetDetectorProvider

### ISSUE THREAD

**Issue by fabiobtex** [ltdrdata/ComfyUI-Impact-Pack#107]
I can't install this node, i was working perfectly before, i can't make the new node to work, there's not even a workflow showing it working, I know i should edit the impact-pack.ini but that doesn't work

**Comment by ltdrdata** [comment]
1. Is there a specific reason for using MMDetDetectorProvider? This node is provided only for compatibility reasons, and if package dependency issues arise in the future, it will no longer be supported.

2. When starting ComfyUI, what error messages are appearing in the terminal?

**Comment by fabiobtex** [comment]
> 

I was getting better results with the old node but i'm learning. Now you need to write what you want to chance, i guess.

When i change "impact-pack.ini" line from "true" to "false, the whole node package is gone, like an uninstall. Am i doing something wrong?

**Comment by ltdrdata** [comment]
> I was getting better results with the old node but i'm learning. Now you need to write what you want to chance, i guess.
> 
> When i change "impact-pack.ini" line from "true" to "false, the whole node package is gone, like an uninstall. Am i doing something wrong?

That indicates a failure in loading the Impact Pack. The reason MMDet is disabled by default is because its dependent packages are notoriously difficult to install depending on the environment. Therefore, it has been replaced with nodes that serve as alternatives.

The reason for maintaining MMDet is primarily to support users who were already using it as the basis for their installations. Enabling MMDet can lead to difficulties in installation and, even if successful, it can significantly slow down the initial launch time of ComfyUI by several seconds. Therefore, it is recommended to avoid using it whenever possible.
