### ISSUE TITLE
Recieve Image may have a bug? doesn't seem to queue correctly.

### ISSUE THREAD

**Issue by Ferniclestix** [ltdrdata/ComfyUI-Impact-Pack#130]
recieve image node may be bugged, if jobs are queued up it seems to only send the last individually generated image. That or my comfy is being strange again... which isn't all that unusual.

<img width="1585" alt="outpaintbug" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128430314/eebe2245-efb9-4e64-a4d8-51ad5046113e">

https://drive.google.com/file/d/1qwctrp0oQ4nPI5Y59hhnIZikNTRjHB_s/view?usp=sharing

https://youtu.be/Ls7NhZ_dkr8  If none of the other stuff makes sense lol

**Comment by Ferniclestix** [comment]
Additional, looks like the Reciever node is not sending its updated status to the part of comfyUI that checks for changes in a node? or something like that.
Tried changing connected nodes and to force the blend to refresh, but it still sends original image. :<

**Comment by Ferniclestix** [comment]
additional additional.
Latent receiver is an image receiver node  in right click menu but not in search menu

latent reciever also appears to be 'stuck' on undefined.

**Comment by ltdrdata** [comment]
The Sender/Receiver for Image and Latent, as well as the current frontend operation, are causing some roughness. 
The issue could be resolved by using an autoqueue mechanism where additions occur upon completion, rather than manually adding the queue multiple times.

In the current structure, the execution of a prompt must be completed and reflected in the sender for the appropriate prompt for the next step to be set on the receiver.

Upon reviewing this issue report, I am considering a feasible structure on the backend.

**Comment by Ferniclestix** [comment]
> The Sender/Receiver for Image and Latent, as well as the current frontend operation, are causing some roughness. The issue could be resolved by using an autoqueue mechanism where additions occur upon completion, rather than manually adding the queue multiple times.
> 
> In the current structure, the execution of a prompt must be completed and reflected in the sender for the appropriate prompt for the next step to be set on the receiver.
> 
> Upon reviewing this issue report, I am considering a feasible structure on the backend.

found a workaround, 
<img width="128" alt="Screenshot 2023-08-28 135715" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128430314/df92bb1d-ea59-450b-93e3-4d677da43994">
need to tick this box. it queues if queue hits 0 at end of batch
