### ISSUE TITLE
FEATURE REQ: The opposite version of 'switch'

### ISSUE THREAD

**Issue by mijuku233** [ltdrdata/ComfyUI-Impact-Pack#149]
Contrary to the 'switch' function, with a single input and multiple outputs, switch the 'input' to different 'outputs'

**Comment by ltdrdata** [comment]
Is it referring to selecting a execution path for the input?

**Comment by mijuku233** [comment]
like this
[Switch.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12556697/Switch.zip)

**Comment by mijuku233** [comment]
> Is it referring to selecting a execution path for the input?

[Switch.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12556708/Switch.zip)
like this

**Comment by mijuku233** [comment]
@ltdrdata like this
[Switch.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12556745/Switch.zip)

**Comment by ltdrdata** [comment]
> @ltdrdata like this [Switch.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12556745/Switch.zip)

I also know what it is the shape to be. However, when it comes to sending the output as selected by a switch for the input, it pertains to what happens to the remaining output parts.

It's about whether you want to block the execution of the output for the unselected location.

**Comment by mijuku233** [comment]
@ltdrdata Turn an input into multiple outputs, and choose which to enable and which to disable.
After the output is disabled, the connected nodes cannot get the input, which may cause some node errors, but it should not affect the use.

**Comment by ltdrdata** [comment]
https://www.youtube.com/watch?v=KLe1hShwVDs

I am pleased to announce the addition of this feature. Due to the constraints of ComfyUI, implementing this functionality wasn't as straightforward as you requested, so there are still some functional limitations in place.

Originally, if no input was provided, the workflow wouldn't just throw an error but also halt the execution. To work around this, at the point of queuing the prompt, it behaves as if the connections other than the selected one have been disconnected.
