### ISSUE TITLE
Switch any forgets type on workflow load.

### ISSUE THREAD

**Issue by Ferniclestix** [ltdrdata/ComfyUI-Impact-Pack#158]
Sometimes my workflow seems to forget what type it is on the contextual Switch (any)
I can't get it to reliably bug out but it sometimes just drops connections, specifically noticed with image switching.

https://drive.google.com/file/d/1C4uLZ89NdDuQp9RQ1HTdKHxHlcHhWulG/view?usp=sharing

On the "main router" group, this switch just bugged out with this workflow and disconnected the image futher up the line where it forgot what type it was supposed to be.

ComfyUI portable, up to date as of a couple of hours ago.  love the switch any btw, let me reduce my switches number :D 

PS: might be an idea to set the default trigger on switches to execute. on prompt throws errors for me, could be im using them wrong? no idea.

**Comment by ltdrdata** [comment]
This issue requires modification of reroute node. It's related to randomness of loading order.

There is a solution but I didn't PRed because the code will be ugly or it requires
heavy fix.

I recommend pythongosssss's reroute node instead of builtin reroute for switch.

For safety, I should patch it to prevent the switch node from connecting to the built-in reroute node later.

**Comment by Ferniclestix** [comment]
need a button to replace all my reroutes :<

**Comment by ltdrdata** [comment]
> need a button to replace all my reroutes :<

Try requesting it here: https://github.com/pythongosssss/ComfyUI-Custom-Scripts. He might consider creating such a feature.

**Comment by Linaghan34** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/127322778/2b108c84-752b-4be5-a8b7-ff367fd3426a)
 请问我跑这个ComfyUI-Impact-Pack/ComfyUI-Inspire-Pack - Workflow: Auto Handfix 流程时，所有都更新过，但是报错
