### ISSUE TITLE
FaceDetailer - any "confidence ratio" option?

### ISSUE THREAD

**Issue by alenknight** [ltdrdata/ComfyUI-Impact-Pack#161]
new to Comfyui from A4.... and using the FaceDetailer in Impact-Pack... i'm struggling to find how to set the confidence ratio?  particularly "Detection model confidence threshold"?   

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/22153900/22c6b27d-c3bd-451f-a4fa-38bdac543453)

i'm guessing this would be somewhere in the Facedetailer node?
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/22153900/dbe861fb-b526-43c1-9074-063d6a234dfa)

**Comment by ltdrdata** [comment]
bbox_threshold and sam_threshold are confidence for each detection model.

**Comment by alenknight** [comment]
> bbox_threshold and sam_threshold are confidence for each detection model.

that worked!  thank you!  any info on Min/Max area ratio?  (in order to define how big/small to filter out hands/faces in an image?)

**Comment by ltdrdata** [comment]
> > bbox_threshold and sam_threshold are confidence for each detection model.
> 
> that worked! thank you! any info on Min/Max area ratio? (in order to define how big/small to filter out hands/faces in an image?)

I'd added `length_percent` filter. 7e6a404856278217faf56bfa427f6d92249f43d5

![length_percent](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/3c6be256-36dd-49db-8a1a-833977711ae1)

To achieve detailed control using the `SEGS filter`, you should use "Detailer" instead of "FaceDetailer."

https://www.youtube.com/watch?v=9GSQlxZFrLI
