### ISSUE TITLE
Eval Int to Any Switch Doesn't Work

### ISSUE THREAD

**Issue by VikingTechLLC** [ltdrdata/ComfyUI-Impact-Pack#165]
I've tried a few different ways, is this expected?

Switch (any) (with widget) = OK
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/84103587/8823bd64-2eec-4595-89ef-d3134c26ef2e)

ImpactInt (with widget) > Switch (any) = OK
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/84103587/29e406c0-843f-43b4-92de-6dc4aa72a16f)

Eval Int > Switch (any) = nonetype error
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/84103587/12c90305-cc42-4f68-9e1c-49a7441a10db)

Eval Int > ImpactInt > Switch (any) = nonetype error
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/84103587/62750854-f9b3-4ce7-aadf-8cf14a6c9500)

**Comment by ltdrdata** [comment]
The reason for providing the option `select_on_prompt` is that the selection should be made at the moment when **queue prompt** becomes the active prompt. The role of `select_on_prompt` is to treat all inputs other than the one selected at the time of `queue prompt` as if they were cut off.

In ComfyUI, the nodes to be executed along the connection lines are determined. When using a switch node, even if it is in an incomplete state due to connections from the output nodes, it attempts execution and causes issues.

`eval` yields its value not at the time of **queue prompt** but at the time of execution. As a result, when there is a mismatch between the input left at the time of **queue prompt** and the input selected by `eval`, it causes issues because it outputs an unconnected (i.e., None) result.

**Comment by VikingTechLLC** [comment]
I've used the information you provided and got workarounds for several situations in my workflow, but still hitting some roadblocks.
Do you think it would be possible to have any eval type node work which with the select_on_prompt (currently existing or a newly created one)?  Or is that not possible?

**Comment by ltdrdata** [comment]
> I've used the information you provided and got workarounds for several situations in my workflow, but still hitting some roadblocks. Do you think it would be possible to have any eval type node work which with the select_on_prompt (currently existing or a newly created one)? Or is that not possible?

When using an eval node that can operate within a browser, it is technically possible to support it. However, it's currently on hold because its utility will be useless once [PR931](https://github.com/comfyanonymous/ComfyUI/pull/931) is merged.

**Comment by VikingTechLLC** [comment]
Oh wow that is really great to see that's being worked on by several people!  Thanks for the heads up regarding it!
