### ISSUE TITLE
node types were not found

### ISSUE THREAD

**Issue by PhantomToG** [ltdrdata/ComfyUI-Impact-Pack#175]
When I launch ComfyUI there is an error:
When loading the graph, the following node types were not found:
UltralyticsDetectorProvider
Nodes that have failed to load will show as red on the graph.

When I go to 'Install Missing Custom Nodes' I get this:
NOTE:MMDetDetectorProvider and other legacy nodes are disabled by default. If you want to activate these nodes and use them, please edit the impact-pack.ini file in the ComfyUI-Impact-Pack directory and change 'mmdet_skip = True' to 'mmdet_skip = False.'

When I edit the file and change it from 'True' to 'False' and entry ComfyUI, I get this error:
When loading the graph, the following node types were not found:
SAMLoader
FaceDetailer
UltralyticsDetectorProvider
Nodes that have failed to load will show as red on the graph.

My terminal says this:
(IMPORT FAILED): /Users/phantomg/ComfyUI/custom_nodes/ComfyUI-Impact-Pack

Everything is up to date

<img width="463" alt="Screenshot 2023-09-21 at 11 23 54" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/145672257/5d7dc0be-4929-4e09-aa93-68f8d60d63bd">

<img width="1190" alt="Screenshot 2023-09-21 at 13 28 46" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/145672257/595efa9e-93a1-4f09-a4b3-b29de513053e">

<img width="1512" alt="Screenshot 2023-09-21 at 13 26 39" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/145672257/e79bc7a8-f345-4c40-a57c-b2069883ccc9">

**Comment by ltdrdata** [comment]
Setting `mmdet_skip = False` will install the infamous `pycocotools/mmcv/mmdet`, well-known for its notoriety, in order to use nodes based on the `mmdet` framework. Fortunately, if these packages are successfully installed on your system, you can activate these nodes; otherwise, the Impact Pack itself may fail to run due to missing dependencies.

The main reason for keeping it disabled by default and transitioning to a node configuration based on Ultralytics, which no longer depends on mmdet, is to avoid these issues.

It is strongly recommended to keep that option as `mmdet_skip = True`. The existing nodes are provided solely for the sake of compatibility with old workflows and offer no advantages whatsoever.

**Comment by PhantomToG** [comment]
Okay, I keep it as 'True'. 
I don't have the (IMPORT FAILED) problem anymore.
I still have this problem:
When loading the graph, the following node types were not found:
UltralyticsDetectorProvider
Nodes that have failed to load will show as red on the graph.

Everything is up to date and installed correctly. What can I do?

**Comment by PhantomToG** [comment]
FIXED

I tried the solution from https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/163 and it worked for me.
