### ISSUE TITLE
how to use different denoise and seed when running TwoAdvancedSamplersForMask

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#233]
how to use different denoise and seed when running TwoAdvancedSamplersForMask
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/47c27b6d-0b96-4251-bf3a-481503a299d2)

I want to control different denoise and seed like TwoSamplersForMask

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/1581b674-5e02-4a19-9f0b-a3906e210b3c)

**Comment by ltdrdata** [comment]
You can't. That is the limitation of that node.

**Comment by ltdrdata** [comment]
> You can't. That is the limitation of that node.

But you can use regional samplers

https://youtu.be/06c5x_oqxCc?feature=shared

https://youtu.be/YTLc7YIwy6w?feature=shared

**Comment by xueqing0622** [comment]
> You can't. That is the limitation of that node.

ok, thx! I spend time to learn your nodes, There's a lot of knowledge in there that I need to ask you about.

**Comment by xueqing0622** [comment]
becauseTwoAdvancedSamplersForMask applies alternately at each step, 
Then the advantage of its advantage is to generate a more natural picture, there will be no sense of patch effect,
 I so understand right?

**Comment by ltdrdata** [comment]
> becauseTwoAdvancedSamplersForMask applies alternately at each step,
> Then the advantage of its advantage is to generate a more natural picture, there will be no sense of patch effect,
> I so understand right?

The original concept of `TwoSamplerForMask` emerged as a way to explore different configurations for CFG, by simply splitting the regions based on masks and sequentially sampling them one by one.

`TwoAdvancedSamplerForMask` served as an experimental precursor to the `Regional Sampler`. Instead of completely isolating each mask region for sampling, it was designed to alternate between them at each step, aiming to create a more natural sampling approach. The current `Regional Sampler` builds upon this idea, allowing for two or more regions and incorporating various tricks to address its limitations.

**Comment by xueqing0622** [comment]
Thanks for the answer, and your nodes are getting better.
