### ISSUE TITLE
how about make regional conditioning  support lora?

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#235]
https://www.youtube.com/watch?v=odW4M8fitUc
this is good tutor for regional compose, and regional conditioning  very useful, 
how about make regional conditioning  support lora? make each regional conditioning support lora like ImpactWildcarEncode,
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/cd96c650-e05d-4463-81ad-38ba0223f2c3)

**Comment by ltdrdata** [comment]
That is technically impossible. In the current architecture, at the conditioning level, it's not possible to hold LoRA information. That's why something like a `Regional Sampler` is needed.

I made a suggestion to Comfy about incorporating LoRA into conditioning, and he is considering it. If that gets added in the future, I will also take it into account.

**Comment by xueqing0622** [comment]
Thx, hope it add incorporating LoRA into conditioning  in the future,
