### ISSUE TITLE
Wildcards not fully resolved

### ISSUE THREAD

**Issue by AsuraAce** [ltdrdata/ComfyUI-Impact-Pack#255]
hey, it seems wildcards dont get fully resolved. only the upper level wildcards will be resolved but if this leads to another one, it will only print the wildcard itself:

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/13394741/10363738-2757-415f-b983-7ce4736ade57)

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/13394741/5bf807ee-a197-4606-adff-5ca6b03f2e1f)

**Comment by ltdrdata** [comment]
Directory itself cannot be wildcard.

in that case that should be like this.

`__custom/partiprompts/perspective/*__`

**Comment by AsuraAce** [comment]
__custom/partiprompts/perspective__ is pointing to a file not a directory. 

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/13394741/c8920b56-36de-42a8-b423-3984c4990c41)

that file than points to files within the ".../perspective" directory.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/13394741/65c50daf-77dc-4544-ac79-afb91043607a)

those wildcards work fine with a1111. will test your methods later and will let you know whether it worked with comfy and a1111, thank you for the quick response.

**Comment by ltdrdata** [comment]
> **custom/partiprompts/perspective** is pointing to a file not a directory.
> 
> ![image](https://user-images.githubusercontent.com/13394741/278915207-c8920b56-36de-42a8-b423-3984c4990c41.png)
> 
> that file than points to files within the ".../perspective" directory.
> 
> ![image](https://user-images.githubusercontent.com/13394741/278915145-65c50daf-77dc-4544-ac79-afb91043607a.png)
> 
> those wildcards work fine with a1111. will test your methods later and will let you know whether it worked with comfy and a1111, thank you for the quick response.

Oh.. I missed `custom/partiprompts/perspective.txt`  file.
In that case the pattern should be `__*/partiprompts/perspective__`

Impact Wildcard doesn't support relative path.

Omitting parts of the path in a wildcard is only allowed when it's neither a subdirectory nor an `*`.

If, for example, you specify `__perspective__` instead of `__partiPrompts/perspective__`, and the pattern matching for `perspective` is unsuccessful, then it attempts to match `__*/perspective__` only for this specific case.
(But, I recommend `__custom/partiPrompts/perspective__` this is more clear and efficient. `*` can be dangerous. Or just move `wildcards/custom` dir to root of `custom_wildcards` or `wildcards`)

The intentional exclusion of `/` or `*` for explicitly specifying patterns is in place to prevent unintentional misapplication of wildcards.
