### ISSUE TITLE
Detector labels - throwing error?

### ISSUE THREAD

**Issue by alenknight** [ltdrdata/ComfyUI-Impact-Pack#257]
when I run detector labels tutorial and the workflow... basically it's only picking up "person" and a very limited number of items (in this case with a random image of a person shopping... it's picking up person and 'kite').  if I try something like "bag" it throws this error.  I'm guessing this is due to it not finding it?  is there a way to get comfyui to then ignore it and just keep running the workflow?  this would become an issue if I'm passing images from a render dynamically and it doesn't find something....  when doing a batch.  

I should note in this image, SEGM thought the bag was a "kite". if I throw kite in there, then it runs.... but stuff like face, glasses, hair, all get ignored and throws this “index out of range” error. is that normal?

<img width="994" alt="Screenshot 2023-10-31 at 2 10 26 PM" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/22153900/7c29117a-a26f-408d-9a5c-8267fa182b5e">

**Comment by ltdrdata** [comment]
`SEGS to Mask List` has been updated to return a list containing an empty mask when SEGS is empty instead of an empty list. 

However, this approach is not possible for `From SEG_ELT`. Instead, I introduce a method to resolve it using the `Control Bridge`. Please be cautious, as the `Control Bridge` is a node that controls the mute state of connected nodes, and it uses a trick involving adding a queue in this process. If there are nodes in the previous section that change widget states, like randomize, it can become messy when used, so you should be careful. 
`Control Bridge` is experimental node yet.

In fact, the `From SEG_ELT` part is purely for information and can be removed.


![workflow](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/a480c5a1-9757-4876-ab00-b32a6d0f3d8f)

**Comment by alenknight** [comment]
awesome.  thanks for the fix.  works in that there's no more error now.  also greatly appreciate the explanation about ELT.  yeah I forgot it's optional as it's just for info-gathering.... thanks again!
