### ISSUE TITLE
 Could not install packages due to an OSError: [WinError 5] Access is denied when using Stability Matrix

### ISSUE THREAD

**Issue by stanica** [ltdrdata/ComfyUI-Impact-Pack#287]
Getting this error when launching Comfy UI through Stability Matrix'

```
Installing collected packages: opencv-python, pandas, thop, seaborn, ultralytics
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\user\\AppData\\Roaming\\StabilityMatrix\\Packages\\ComfyUI\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
Check the permissions.

### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
Traceback (most recent call last):
  Recommended to delete the path and restart ComfyUI.
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 406, in <module>
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.
    import impact.subpack_nodes

  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
---------------------------------
    import impact.subcore as subcore
  File "C:\Users\user\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 10, in <module>
---------------------------------
    from ultralytics import YOLO

ModuleNotFoundError: No module named 'ultralytics'```

**Comment by ltdrdata** [comment]
Please attach the comfyui.log file generated during the first restart after deleting and reinstalling the Impact Pack in Manager.
I suspect that there might be an issue with the paths due to the execution in StabilityMatrix.

**Comment by ltdrdata** [comment]
After a more detailed analysis, I've found that this limitation occurs specifically when executed in StabilityMatrix on Windows. To prevent permission issues, ComfyUI is set up to allow the installation of packages for custom nodes before other modules are installed. However, StabilityMatrix imports ComfyUI after using many other modules, causing the installation script to run too late.

To prevent this error, you need to install the `ultralytics` package in the Python environment used by StabilityMatrix directly with StabilityMatrix turned off.

**Comment by stanica** [comment]
> To prevent this error, you need to install the `ultralytics` package in the Python environment used by StabilityMatrix directly with StabilityMatrix turned off.

This is probably outside your scope but can you point me in the right direction to figure out how to do this?

Edit: Nevermind, chatgpt helped me figure this out. Thanks!

**Comment by mtrak** [comment]
Hey, I had this exact same error with onnxruntime.
The problem is that the DLL file is still being used by ComfyUI, so Windows won't let it be replaced. The best way to fix it is to completely close ComfyUI first (make sure nothing is running in the background).
Then open PowerShell as Administrator and run these commands:
cd "D:\ComfyUI_windows_portable\python_embeded"
.\python.exe -m pip uninstall onnxruntime onnxruntime-gpu -y
.\python.exe -m pip install onnxruntime-gpu --no-deps --force-reinstall
If it still complains about permissions, try this version instead:
.\python.exe -m pip install onnxruntime-gpu==1.18.0 --no-deps --force-reinstall
That usually solves it for me. After installing, just restart ComfyUI with run_nvidia_gpu.bat and try again.
Let me know if it works!
