### ISSUE TITLE
Face shaping plug-in matches Eff KSampler face collapse

### ISSUE THREAD

**Issue by sebord** [ltdrdata/ComfyUI-Impact-Pack#288]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/104607562/58892dc7-a750-4748-a329-9041ec9228f3)

**Comment by ltdrdata** [comment]
Check cropped enhanned alpha.

**Comment by sebord** [comment]
Sorry, what do you mean? I'm a newbie and don't understand very well.

**Comment by ltdrdata** [comment]
> Sorry, what do you mean? I'm a newbie and don't understand very well.

add `Preview Image` node and connect to `cropped_enhanced_alpha` output of FaceDetailer node.

**Comment by sebord** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/104607562/a8cc167d-102d-457b-a968-37bcbc4f740c)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/104607562/6821e0e8-1834-48bf-a676-6a18f1ef721e)

**Comment by sebord** [comment]
But when I use ordinary Kasmpler, the effect is good
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/104607562/b19cbc53-ab12-4488-a054-02ee3e529eb8)

**Comment by ltdrdata** [comment]
> ![image](https://user-images.githubusercontent.com/104607562/284050744-a8cc167d-102d-457b-a968-37bcbc4f740c.png) ![image](https://user-images.githubusercontent.com/104607562/284050770-6821e0e8-1834-48bf-a676-6a18f1ef721e.png)

It seems that this is due to the application of controlnet in the positive/negative conditioning delivered to the Detailer. 

The Detailer enlarges small portions of the image and redraws them using prompts with controlnet applied for the entire image. Naturally, using prompts with controlnet for the entire image would result in strange outcomes.

Please use positive/negative conditioning without the application of controlnet for the input.

**Comment by sebord** [comment]
OK, I'll try it, thank you
