### ISSUE TITLE
Torch parse_version error 

### ISSUE THREAD

**Issue by diaopal** [ltdrdata/ComfyUI-Impact-Pack#299]
Getting this error:
```
### Loading: ComfyUI-Impact-Pack (V4.31.1)
WARNING  failure for parse_version(2.1.0.dev20230718+cu121), reverting to deprecated pkg_resources: invalid literal for int() with base 10: ''
WARNING  failure for parse_version(2.1.0.dev20230718+cu121), reverting to deprecated pkg_resources: invalid literal for int() with base 10: ''
WARNING  failure for parse_version(2.1.0.dev20230718+cu121), reverting to deprecated pkg_resources: invalid literal for int() with base 10: ''
```

**Comment by ltdrdata** [comment]
That's not an issue with the Impact Pack. It seems to be a package-related issue.

First, disable the Impact Pack and see if the error persists.

**Comment by diaopal** [comment]
No warnings/errors if I disable Impact Pack.

**Comment by ltdrdata** [comment]
That is an issue with the ultralytics package. It is occurring because you are using the nightly version of PyTorch instead of the official released version. It is just a warning, so you can ignore it.

https://github.com/ultralytics/ultralytics/blob/830037e0ce1513fc0abcb72dedc902d8509906cb/ultralytics/utils/checks.py#L78
