### ISSUE TITLE
Upscaler being unpredictable

### ISSUE THREAD

**Issue by Kaharos94** [ltdrdata/ComfyUI-Impact-Pack#3]
I found the upscale to guidesize very unpredictable - sometimes deciding not to upscale at all even if it should, sometimes overblowing the resolution extremely. 
I messed around with it and changed the upscale value in the code to use the cropped area height or width instead of using the BBox height and width to get the final resolution, which then upscales it to the proper guide size , which seems to work better. 
` upscale = guide_size/min(h,w) `

**Comment by ltdrdata** [comment]
oops.. I made a mistake..

Original code works as similar as your modification. But, it became a bug because I changed bbox_size to bbox it self. 

One thing. I do scale up based on detected bbox size instead image size.
Image size is cropped size. So little bit differrent.

I'll fix it soon.. thx

**Comment by ltdrdata** [comment]
I fixed this issue. Try current version.

**Comment by Kaharos94** [comment]
![image](https://user-images.githubusercontent.com/80826189/231459666-d9affd1f-64a7-4c4a-87eb-d69e272971df.png)

With the new version, it's still quite unpredictable - I might be misunderstanding what you're meaning with the guidesize though. From the explanation I thought it's supposed to upscale to that resolution. Obviously this specific image isn't the perfect use case as it gave me a portrait image with quite the big face anyway. My problem with upscaling with the BBox is that the guidesize isn't intuitive to use.

![image](https://user-images.githubusercontent.com/80826189/231461580-59ab7fe0-aaee-4b88-8ef1-eaa0e16e13bb.png)
Even on a smaller face, it still going really damn big. 

Might be just me that is a bit stupid though.

**Comment by ltdrdata** [comment]
The reason why the face appears broken is due to the fact that the source data contains a face region that is too small to be drawn with intricate details, therefore, if a face is large enough, it does not require to be redrawn at a larger size, while small faces are only enlarged to reach the guide_size limit. As a result of this, it is common for small faces to be of high quality resolution.

On the other hand, if the drawn face upscaled to excessively large resolution, it is likely due to the crop_size parameter. This parameter determines how many times the original detected face size should be cropped, in order for the model to recognize the surrounding context and draw a face that is consistent with the given prompt. Initially, the model performed latent upscaling based on the cropped area, but the current approach uses image upscaling instead, which is expected to produce more predictable face sizes without the need for additional upscaling processing.

**Comment by Kaharos94** [comment]
The Crop Region for the second generation was on 2.5 , guide size on 768. I do understand how it's supposed to work now and see how that is useful. Still think it's a bit unpredictable, but that's probably just me.  I'll just modify my install to do it a bit differently then :)

**Comment by ltdrdata** [comment]
I patched about crop_size. Try new version.
And I think the tutorial and explanation in README.md need to be strengthened a bit more.

**Comment by Kaharos94** [comment]
![image](https://user-images.githubusercontent.com/80826189/231503085-e14ac082-6716-4ede-99a4-4343cf4a0583.png)

It's still doing insane sizes, same settings as above. Really, it's just a difference between what you want to have sampled up - I just think it's more predictable if you take the cropped sizes :)

**Comment by ltdrdata** [comment]
As you know that, predictabilty is not main purpose. But, maybe I can provide as optional feature.

**Comment by Kaharos94** [comment]
Would be cool, it's quite helpful if you're using the detailer as a general node to run over generated images and not only doing face restoration - you know how it is, you never get 100% what you're expecting and if you suddenly got a portrait in your queue and it takes 15 minutes to sample it , it's a bit annoying.

**Comment by ltdrdata** [comment]
Perhaps you have already tried it, but I added the "guide_size_for" parameter. I am agreed with that it can be quite useful for general purpose detection and detailing.

**Comment by Kaharos94** [comment]
Yup! works perfectly! thanks for the quick improvement :)
