### ISSUE TITLE
Unexpected behaviour with detailers

### ISSUE THREAD

**Issue by Bocian-1** [ltdrdata/ComfyUI-Impact-Pack#35]
I have the following setup:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/70019596/95d1b494-fc62-4798-b18f-b0581df30d5b)
I would expect this to run each detailer on a different face as marked with the mask in the Image Loader. After some operations, it results in the masks I want as demonstrated on the preview nodes. However, both detailers run for both faces for some reason.

**Comment by ltdrdata** [comment]
> I have the following setup: ![image](https://user-images.githubusercontent.com/70019596/250198662-95d1b494-fc62-4798-b18f-b0581df30d5b.png) I would expect this to run each detailer on a different face as marked with the mask in the Image Loader. After some operations, it results in the masks I want as demonstrated on the preview nodes. However, both detailers run for both faces for some reason.

Have you tried strong denoise? I recommend **DetailerDebug (SEGS/pipe)** to check the error.
It will show what is refined image for each SEGS.

**Comment by ltdrdata** [comment]
I tried this. Little bit different approach with yours.
![different](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/c2058318-d6ff-4132-92e1-c809f6e0f0e9)

And this is the workflow.
![ComfyUI_00027_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/88809226-0b92-4ada-93d7-6cf02d028264)

**Comment by Bocian-1** [comment]
Checking with the debug nodes it does look like the detailers don't actually affect the areas they shouldn't, even though they run there anyway wasting some time.
Using MASK to SEGS like in your example avoids that. Thank you.

**Comment by ltdrdata** [comment]
> Checking with the debug nodes it does look like the detailers don't actually affect the areas they shouldn't, even though they run there anyway wasting some time. Using MASK to SEGS like in your example avoids that. Thank you.

I recently updated Impact Pack, and I'm not sure if it's because of that or not, but when I followed your workflow, it worked correctly.

![b](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/1bc34aab-7383-4359-98b7-bae88bb29621)
![a](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/5a7aeaec-6607-48cb-9bbe-3406c0eeb05a)

![ComfyUI_00021_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/4301b571-3631-410a-b64b-5010876a99ad)

**Comment by Bocian-1** [comment]
The result was, and is correct, yes, but that is not the issue.
The first detailer runs for both faces and then the second does so as well:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/70019596/e3c434f9-76d5-4a20-9229-9e513d121abd)
This would ideally not happen, as there are only 2 faces, not 4. The first detailer should only run on the face that is not masked on the preview bridge, and the second on the masked face. Only the correct face is then pasted by each detailer so the end result is correct. The problem is them running on the other face, which is unnecessary as the result isn't even used. Using Mask to Segs works, but for some reason, Bitwise(Segs & Mask) doesn't.

This is with Mask to Segs:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/70019596/62a583c0-bb27-4d28-b839-0c408ecd845c)

**Comment by ltdrdata** [comment]
Oh... I get it what are you talking about.

Because bitwise operator perform bitwise operation simply for mask in the SEGS. It won't remove SEGS itself. That is the reason.

Empty masked SEGS
 can be manipulated in the future. So I am keeping it.

But, I need to update skip detailing if mask is empty.
