### ISSUE TITLE
Error - mmcv module not found, installing manually windows python 310 venv

### ISSUE THREAD

**Issue by TECozens** [ltdrdata/ComfyUI-Impact-Pack#36]
**The following error is seen when installing with a venv install.py**
was resolved locally when I installed mmcv manually.

`ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'F:\\Generative AI\\ComfyUI\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
Check the permissions.`

> Traceback (most recent call last):
  File "F:\Generative AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 86, in ensure_mmdet_package
    import mmcv
ModuleNotFoundError: No module named 'mmcv'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "F:\Generative AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 127, in <module>
    install()
  File "F:\Generative AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 99, in install
    ensure_mmdet_package()
  File "F:\Generative AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 91, in ensure_mmdet_package
    subprocess.check_call(mim_install + ['mmcv==2.0.0'])
  File "C:\Program Files\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['F:\\Generative AI\\ComfyUI\\venv\\Scripts\\python.exe', '-m', 'mim', 'install', 'mmcv==2.0.0']' returned non-zero exit status 1.

**Comment by ltdrdata** [comment]
Turn off the ComfyUI and execute install script(inside ComfyUI-Impact-Pack) manually.

Windows' file locking system blocking reinstalling running package. And it leads cascade failure of installation.

**Comment by BileFlask** [comment]
I had this same issue and I believe it was due to my Python installation taking precedence over the instance embedded in the ComfyUI portable - I think it may have been trying to write the packages to my C:\Program Files\Python310 folder, to which it likely did not have access. I think this is the case because when I ran the installer script within the impact directory, it told me all of the packages were already installed, which they were - in my Program Files site-packages folder.

I was able to resolve this by manually executing the Python.exe from the embedded directory and pointing it to the install.py file in the impact directory:

`PS C:\Users\<scrubbed>\StableDiffusion\ComfyUI_windows_portable\python_embeded> .\python.exe C:\users\<scrubbed>\stablediffusion\comfyui_windows_portable\comfyui\custom_nodes\comfyui-impact-pack\install.py`

Of course, adjust these paths accordingly, but this should resolve your issue.

**Comment by Piscabo** [comment]
> PS C:\Users\<scrubbed>\StableDiffusion\ComfyUI_windows_portable\python_embeded> .\python.exe C:\users\<scrubbed>\stablediffusion\comfyui_windows_portable\comfyui\custom_nodes\comfyui-impact-pack\install.py

I still get this? I think has to do with CUDA version?
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv
  Running setup.py clean for mmcv
Failed to build mmcv
ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "C:\AI_Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 86, in ensure_mmdet_package
    import mmcv
ModuleNotFoundError: No module named 'mmcv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI_Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 127, in <module>
    install()
  File "C:\AI_Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 99, in install
    ensure_mmdet_package()
  File "C:\AI_Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 91, in ensure_mmdet_package
    subprocess.check_call(mim_install + ['mmcv==2.0.0'])
  File "subprocess.py", line 413, in check_call
subprocess.CalledProcessError: Command '['C:\\AI_Files\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-s', '-m', 'mim', 'install', 'mmcv==2.0.0']' returned non-zero exit status 1.

**Comment by ltdrdata** [comment]
I recently updated ComfyUI-Manager. If you update both ComfyUI and ComfyUI-Manager and install the Impact Pack through ComfyUI-Manager, you will no longer experience that issue.
