### ISSUE TITLE
Wildcard Processor requires ImpactInt

### ISSUE THREAD

**Issue by Pojo267** [ltdrdata/ComfyUI-Impact-Pack#367]
I used to be able to use any seed or int for the Wildcard processor seed. Now when I use anything other than ImpactInt, I get a print stating that I can't use anything but an ImpactInt or Primitive Node. Why has this suddenly changed? I can't use the wildcard node within my workflows anymore.

**Comment by ltdrdata** [comment]
> I used to be able to use any seed or int for the Wildcard processor seed. Now when I use anything other than ImpactInt, I get a print stating that I can't use anything but an ImpactInt or Primitive Node. Why has this suddenly changed? I can't use the wildcard node within my workflows anymore.

In the past, if you connected a node other than Primitive node or ImpactInt, it would have malfunctioned.

The primary purpose of Impact Wildcard is to include populated text in the workflow. Therefore, it cannot rely on data generated during the execution of the workflow. The exception to allow ImpactInt, in addition to the Primitive node, is to facilitate value resetting through ImpactValueSender and allow the structure to restart the workflow.

Impact Wildcard does not support the use of any arbitrary node other than the Primitive node or ImpactInt because it cannot guarantee that its value is determined before the execution of the workflow.
