### ISSUE TITLE
Is there a way to only repaint one face?

### ISSUE THREAD

**Issue by oceanusXXD** [ltdrdata/ComfyUI-Impact-Pack#382]
i just want to repaint the foremost face,but it recognizes many faces,
![1702973253116](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/116332761/43d516cb-a54e-4172-a2c3-1b7d084f47d6)
have any option like webui "Mask only the top k largest"
![1702973006163](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/116332761/0edfaa62-19e7-4224-88d6-85bc46b9fe17)

**Comment by ltdrdata** [comment]
There are various ways.
The simplest way is to increase the `drop_size`.
Items smaller than the `drop_size` will be filtered out and excluded from the detailing target.

A sophisticated approach is to directly manipulate SEGS instead of using FaceDetailer and incorporating Detailer.
https://www.youtube.com/watch?v=9GSQlxZFrLI
