### ISSUE TITLE
TypeError: Cannot handle this data type: (1, 1, 512, 3), |u1

### ISSUE THREAD

**Issue by pear1jam-jpg** [ltdrdata/ComfyUI-Impact-Pack#43]
When batch_size > 1 in Empty Latent Image node and Detailer (SEGS) node exists in pipe then this error occurs
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/125306391/f79d15f4-604a-4ef7-9ecc-20e0bf771069)
p.s.: this is sample workflow from this project (advanced-simple.json).

**Comment by ltdrdata** [comment]
https://www.youtube.com/watch?v=nr7OY0tI3bo

The Impact Pack does not natively support multi-batch due to the slightly complex requirement of splitting a single image for processing. Instead, you can use ```Rebatch Latent``` to handle this issue.

This video explains how to solve the problem using Rebatch, demonstrating how it can address the issue at hand.

**Comment by pear1jam-jpg** [comment]
Thanks!
