### ISSUE TITLE
Masks to SEGS bug

### ISSUE THREAD

**Issue by Ne01ynx** [ltdrdata/ComfyUI-Impact-Pack#436]
Whenever you upload 4 masks for 4 images to Mask_to_SEGS, it will take each mask and apply it to every frame, resulting in a total of 16 frames. But don't we have Mask_to_SEGS for AnimateDiff for that purpose?

Well, no. Mask_to_SEGS for AnimateDiff works weirdly. When you upload masks in batch, it merges all masks into one and applies that single mask to every frame in the video.

Should it not take masks one by one for the corresponding keyframe?

**Comment by poisenbery** [comment]
Can you share the workflow so I can try to troubleshoot?

If you pass the masks as a batch, it will "doit" to each mask in the list over all items, which explains why you are getting 16 frames for 4 masks.

But if you pass them as a list, it should treat the entire list as just 1 object (instead of 4 separate objects like in batch)

I'm fairly confident this can be solved by passing the masks as a list, but I want to be sure.

**Comment by ltdrdata** [comment]
It's not a bug. It's an intentional mode.

If you do not want combined mask. 
Set masking mode as `Combine neighboring frame`. When using this mode, instead of combining the entire frame, it combines the frames before and after for each frame.
I don't recommend `Don't combine`.  There are occasional frames where detection fails, and in such cases, the corresponding frame experiences a failure in inpainting.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/838adffd-5297-4939-8ad4-488bdafe5bcf)
