### ISSUE TITLE
too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by linesword** [ltdrdata/ComfyUI-Impact-Pack#456]
erorr:

File "/root/autodl-tmp/custom_nodes/ComfyUI-Impact-Pack/modules/impact/segs_nodes.py", line 1045, in doit
    result = core.mask_to_segs(mask, combined, crop_factor, bbox_fill, drop_size, is_contour=contour_fill)
  File "/root/autodl-tmp/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 979, in mask_to_segs
    contours, ctree = cv2.findContours(mask_i_uint8, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack (expected 2)

workflow: 

[workflow_animatediff_fixface.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/14080657/workflow_animatediff_fixface.json)

Comfyui Hash: 9321198da6c191fab0ab3ea39e626c9e3d9053d3  Date:   Mon Jan 29 00:24:53 2024

ComfyUI-Impact-Pack: cc7812bcfe3b9f8fbb2559f2c9ad62768110f171  Date:   Sat Jan 27 18:33:57 2024

**Comment by ltdrdata** [comment]
> erorr:
> 
> File "/root/autodl-tmp/custom_nodes/ComfyUI-Impact-Pack/modules/impact/segs_nodes.py", line 1045, in doit result = core.mask_to_segs(mask, combined, crop_factor, bbox_fill, drop_size, is_contour=contour_fill) File "/root/autodl-tmp/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 979, in mask_to_segs contours, ctree = cv2.findContours(mask_i_uint8, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE) ValueError: too many values to unpack (expected 2)
> 
> workflow:
> 
> [workflow_animatediff_fixface.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/14080657/workflow_animatediff_fixface.json)
> 
> Comfyui Hash: 9321198da6c191fab0ab3ea39e626c9e3d9053d3 Date: Mon Jan 29 00:24:53 2024
> 
> ComfyUI-Impact-Pack: [cc7812b](https://github.com/ltdrdata/ComfyUI-Impact-Pack/commit/cc7812bcfe3b9f8fbb2559f2c9ad62768110f171) Date: Sat Jan 27 18:33:57 2024

It seems your cv2 version is outdated.
Update `opencv-python, opencv-python-headless, opencv-contrib-python` if installed.

When multiple packages related to OpenCV are installed, it's uncertain which version of cv2 will be loaded. If a lower version is loaded, such phenomena may occur. In case multiple installations exist, it's advised to update the respective version.

Personally, I recommend keeping only `opencv-python` and removing the rest of the installations.

In Impact-Pack, while I do include `opencv-python-headless` in the installation, it's due to specific environments where errors occur when using `opencv-python`.

**Comment by linesword** [comment]
Thank you very much, I will update if there is any progress

**Comment by linesword** [comment]
python==3.10 
opencv-python==4.9.0.80
opencv-python-headless==4.9.0.80
opencv-contrib-python==4.9.0.80

Everything is well !
