### ISSUE TITLE
Refreshing wildcards?

### ISSUE THREAD

**Issue by gachapengames** [ltdrdata/ComfyUI-Impact-Pack#492]
Is the only way to refresh wildcards to restart comfy? The refresh button does not refresh them, nor anything else I have tried. Is there any way to refresh the wildcards without restarting?

**Comment by ltdrdata** [comment]
Sure. The refresh button is a built-in feature of ComfyUI and has nothing to do with Impact Pack. Currently, there is no other way except restarting.
I am reluctant to add separate UI elements for infrequent wildcard reloading.

**Comment by DysnomiaDreams** [comment]
I was wondering the same thing, it'd be a useful addition

**Comment by AiLemonPie** [comment]
This is definitely something I'd be interested in as well. I load my models off a network share due to the number of models I use. The initial load of ComfyUI when starting the workflow before anything gets cached takes 10+ minutes. So every time I update my wildcards, I have to wait 10 minutes for everything to get re-fetched from storage.

Having a toggle or some type of config setting that lets the Node reload the wildcard every time it parses wildcards would be a lifesaver.

**Comment by PurplefinNeptuna** [comment]
this is needed in my case. I build nested wildcard, the bottom one might rarely changed, but I always changing the middle one, for example, I might have wildcard `girls` consisted of `characteristic`, `clothing`, `poses` wildcards and it variations. I mostly modify `girls` wildcard, like adding new wildcard of clothing, or divide poses into multiple wildcards. this is kinda hard to do in comfyui because I need to fully restart it to refresh, and I can't run Auto1111 because I always get OOM after 3 images.

**Comment by ltdrdata** [comment]
This is implemented.

Clicking `refresh` in main menu will now refresh the wildcard. However, it does not reset the node cache, so it will not re-execute unless the prompt is modified.

**Comment by tazztone** [comment]
> Clicking `refresh` in main menu will now refresh the wildcard. 

i refreshed with R and also F5 key. wildcard still does not show up. 
![image](https://github.com/user-attachments/assets/5136b388-3a7d-4e33-847e-ffa43f634eaf)
![image](https://github.com/user-attachments/assets/e93dc530-2c3f-419b-8ed9-3d122f43759d)
am i missing smth?

**Comment by GeminiSquishGames** [comment]
> > Clicking `refresh` in main menu will now refresh the wildcard.
> 
> i refreshed with R and also F5 key. wildcard still does not show up.
> am i missing smth?

It doesn't seem to work for me either.

**Comment by ltdrdata** [comment]
![스크린샷 2025-02-13 07-46-06.png](https://github.com/user-attachments/assets/62384ac9-ea2f-44b9-9537-139edc9399f4)


You need to use refresh wildcard menu item not the browser refresh nor refresh node definitions.

**Comment by jprsyt5** [comment]
> ![스크린샷 2025-02-13 07-46-06.png](https://github.com/user-attachments/assets/62384ac9-ea2f-44b9-9537-139edc9399f4)
> 
> You need to use refresh wildcard menu item not the browser refresh nor refresh node definitions.

Sorry to bump this, Is there another way to refresh it? I can't find this anymore.
