### ISSUE TITLE
The populated prompt window doesn't update in ImpactWildcardProcessor node

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [ltdrdata/ComfyUI-Impact-Pack#51]
This was working until I updated to commit 9c13ec6. The functionality is still there, just that you can no longer see what the wildcards are being populated with.

**Comment by TeaCrab** [comment]
I started having this issue after installing [pythongosssss/ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts)

**Comment by GalaxyTimeMachine** [comment]
There was a compatibility problem between them, but that was recently resolved. I don't know if this is a regression or a new problem.

**Comment by GalaxyTimeMachine** [comment]
I can confirm this is caused by the pythongosssss `ComfyUI\web\extensions\pysssss\CustomScripts\presetText.js` again. Removed that and the wildcards populate correctly.

**Comment by GalaxyTimeMachine** [comment]
I've also opened: https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/20

**Comment by gobshyte** [comment]
It would be really nice if this could work in combination with pysssss presetText.js, because they both give different behaviour in batch mode.

For example, if I generate a batch of 10 images, the impact wildcard processor generates them all upfront, and you only see the last prompt out of all 10 as it runs through the batch, so you have no easy way of seeing the prompt for the current image being generated. (Console debug output is the only alternative I know of at the moment and it's not pleasant.)

However, the pythongosss text node DOES allow you to see a prompt for the current image in the batch, which was super nice, and I am sorely missing it now!

An alternative would be some other impact node that shows the current prompt maybe? Or the existing impact node to show the prompt for the current image only?

**Comment by GalaxyTimeMachine** [comment]
> It would be really nice if this could work in combination with pysssss presetText.js, because they both give different behaviour in batch mode.
> 
> For example, if I generate a batch of 10 images, the impact wildcard processor generates them all upfront, and you only see the last prompt out of all 10 as it runs through the batch, so you have no easy way of seeing the prompt for the current image being generated. (Console debug output is the only alternative I know of at the moment and it's not pleasant.)
> 
> However, the pythongosss text node DOES allow you to see a prompt for the current image in the batch, which was super nice, and I am sorely missing it now!
> 
> An alternative would be some other impact node that shows the current prompt maybe? Or the existing impact node to show the prompt for the current image only?

The original issue reported in this has been resolved. You should open a new feature request for what you want.
