### ISSUE TITLE
ImpactWildcardProcessor uses the same prompt in facedetailer

### ISSUE THREAD

**Issue by Rkkss** [ltdrdata/ComfyUI-Impact-Pack#54]
The mode is populate. It uses the same set of prompt for all faces in the whole process instead of random it for each face.
I assume this is how it works but asking anyway. Is there a workaround?

![abc](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/127614350/65affab6-8ea5-490e-ab0a-e8d4aad6bd9d)

**Comment by ltdrdata** [comment]
Because ImpactWildcardProcessor determines prompt on queue prompt.
If you want to apply randomization to each detected face in the detailer, you should utilize the wildcard in the detailer. During this process, the prompts determined will not be saved in the workflow unlike in the ImpactWildcardProcessor.

https://www.youtube.com/watch?v=lVSNJYfvO9o

**Comment by Rkkss** [comment]
If you already provide wildcard(and prompt) in detailer. Can the positive prompt be an empty prompt?

**Comment by Rkkss** [comment]
I updated and it worked.
but when you convert wildcard to input. It doesn't run
