### ISSUE TITLE
Other sam support

### ISSUE THREAD

**Issue by O-O1024** [ltdrdata/ComfyUI-Impact-Pack#541]
Original sam is too slow, now there are some replacement, eg.
fastsam
mobilesam
EfficientSAM

**Comment by ltdrdata** [comment]
Support for EfficientSAM was added, based on this PR.
https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM/pull/32

To utilize EfficientSAM, you must first install the YoloWorld extension. 
And then ESAM feature becomes available after that PR is merged.

**Comment by niko2020** [comment]
Excuse me I'm not sure I correctly understand. It is now possible to use YOLO-World with Impact Pack?
But it is required to install ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM (which I'm afraid causes problems because of depedencies).

**Comment by ltdrdata** [comment]
> Excuse me I'm not sure I correctly understand. It is now possible to use YOLO-World with Impact Pack? But it is required to install ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM (which I'm afraid causes problems because of depedencies).

Yes, to use this, you'll need to install ComfyUI-YoloWorld-EfficientSAM.

Currently, since it's not merged, you can use this instead for immediate use: (my forked version)
https://github.com/ltdrdata/ComfyUI-YoloWorld-EfficientSAM

Test results show that the current dependencies are optimal. If upgraded to even slightly higher versions, it won't be compatible with Python 3.12.
