### ISSUE TITLE
Help：When loading the graph, the following node types were not found: ComfyUI Impact Pack 🔗 Nodes that have failed to load will show as red on the graph.

### ISSUE THREAD

**Issue by CuteBadEgg** [ltdrdata/ComfyUI-Impact-Pack#588]
![20240507-141604](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/46104450/f129c762-fab2-4d25-a563-fe4d85018dce)
When i used ComfyUI Impact Pack, this  bug has appeared!
How to solve it?

**Comment by ltdrdata** [comment]
What is your workflow?
Post it here.


That's very strange. `ComfyUI Impact Pack` is not the name of a node.

**Comment by Dengyinsong** [comment]
me too

**Comment by Dengyinsong** [comment]
> What is your workflow? Post it here.
> 
> That's very strange. `ComfyUI Impact Pack` is not the name of a node.

https://openart.ai/workflows/bear_ill-fated_78/wear-any-outfit-using-ipadapter-v2-workflow/WVF6iWdxYkUursRUllWU here is the workflow

**Comment by ltdrdata** [comment]
> > What is your workflow? Post it here.
> > That's very strange. `ComfyUI Impact Pack` is not the name of a node.
> 
> https://openart.ai/workflows/bear_ill-fated_78/wear-any-outfit-using-ipadapter-v2-workflow/WVF6iWdxYkUursRUllWU here is the workflow

The error message seems to be caused by an extension you installed, I don't know what it is, that is hiding the actual node error and presenting it in a summarized form.

It would be better to check the terminal message to ensure that the Impact Pack is loading correctly.

Show me the `comfyui.log` file.
