### ISSUE TITLE
Impact pack installed but won't load...

### ISSUE THREAD

**Issue by GoldmanOz** [ltdrdata/ComfyUI-Impact-Pack#59]
Using an M1 MacBook Pro and getting this error when loading in to ComfyUI, installed the Impact pack through the Manager, all shows to be ok until I load the UI..then this happens...  Any ideas please ???

<img width="593" alt="Impact Pack" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139660390/faa9405d-e72d-4fa8-8a88-0c1fadb44901">

**Comment by ltdrdata** [comment]
If your network environment is not a special case like a special setup of firewall, it appears to be in a situation where there is a security threat.

Try copying the address from download_url(..) and directly access it in your web browser. The provided path should normally be a valid address for connection, but there seems to be an issue with the SSL certificate.

It's possible that the destination has been altered due to some form of hacking or security breach.

**Comment by GoldmanOz** [comment]
I'm not sure I understand, ComfyUI is loading and working as expected other than the Impact pack, this failure to load is only a read out in the terminal relating to that install not loading, everything else is....I can use Comfy other wise.??

**Comment by ltdrdata** [comment]
> I'm not sure I understand, ComfyUI is loading and working as expected other than the Impact pack, this failure to load is only a read out in the terminal relating to that install not loading, everything else is....I can use Comfy other wise.??

You can manually install and download them, anyway.
The model files should be placed in `models/ultralytics/segm`, `models/ultralytics/bbox`

**Comment by GoldmanOz** [comment]
I got it working...did a google search and worked out how to update the "(_ss1.c:997)> certificate" and it loaded up when I opened Comfy after that...thanks for trying to help..👍🏻

**Comment by ltdrdata** [comment]
> 


That's quite fortunate :) Enjoy then.
