### ISSUE TITLE
What does the guide_size actually do?

### ISSUE THREAD

**Issue by DivinoAG** [ltdrdata/ComfyUI-Impact-Pack#6]
Could anyone explain what _exactly_ the `guide_size` property does? I know the general description from the readme:

> guide_size: This feature attempt detail recovery only when the size of the detected mask is smaller than this value. If the size is larger, this feature increase the resolution and attempt detail recovery.

... but that, figuring if the area is too big to be scaled up is not all it does, and that's not exactly _how it does it_, right? From seeing it at work, I sometimes get logs like `crop region (622, 657) x 1.2340581845389367 -> (704, 768)`, which is bigger than the `256` default value I had set, so if I were to take the readme literally it shouldn't be upscaled at all. All of it makes it seem like it's also being used to determine how large the new render size is in very roundabout way (not quite multiples of the value, since 704 isn't a multiple), as well as the scale ratio, which is a lot of things for one single value to control, and I just can't seem to get it to behave how I'd like.

Could it be possible to get a precise description of everything this property is doing, how is it doing, and could we perhaps have a conversation about whether all these things should not be separated into at least two, maybe even three separate properties to allow more control, and prevent some detail that really needed to be re-rendered to be skipped because it just landed at the wrong upscale ratio? 

Thanks!

**Comment by Kaharos94** [comment]
It depends on what setting you have it on - Itrdata added another one, one "Crop Region" and one "BBox". 
If you set it to Bbox , it's going off of the size of the original BBox, not the cropped region, which is usually bigger than the BBox depending on your crop settings for the bounding box. 

For example , your face is 200 x 200 pixels, you got your crop factor set to 2.5 though, so the cropped area is bigger, but it calculates the upscale from the 200x200. It then upscales the cropped region by the amount to reach a Bounding Box resolution of the guide size. 

If you set the Mode to "Crop region" , you'll reliably upscale the entire crop to the specified size , makes it more predicatble than the bounding box version, but usually uses smaller sizes. 

The upscale is calculated in multiples of 64, which 704 is. If I recall it correctly, it calculates the upscale multiplier by the lower one of height or width, so you still have some variance.

**Comment by DivinoAG** [comment]
Thanks for your answer @Kaharos94, however I'm not positive it's fully answers what I asked. For example, it's still unclear how does it get to the upscaled image size.

On that example I posted it scaled an area of 622 x 657 (in other words, already bigger than 256) up ~1.2 times, to 704 x 768, which mostly just changes the image without actually improving it in any way. Why didn't it simply upscale to something bigger (but still multiple of 64) like 1024 x 1280, which would be more like a 2x upscale that would really improve the image? How can I determine a value that would improve my rendering quality without having to test each image first? More important, how does it get from that value of `256` to the size of 704 x 768 it choose? That's the part that puzzles me.

I guess my issue is that this one variable doesn't provide enough context to really determine what a good value would be without knowing already what the result is, which undercuts the goal of the tool in the first place. 

Wouldn't it be more useful to have a property that lets me determine the maximum image size I'm interested in rendering, and perhaps the desired scaling ratio (or maximum and minimum ratios), which together could be used to determine the rendering size without any guess work? So if I select a maximum render size of 1280px, maximum ratio of 4x and minimum of 2x, then the plugin could use these numbers to find the biggest (for best quality) image size that fits in that range of scaling ratios. If the smallest 2x scaling is bigger than 1280, it skips because the detected area is too big.

It would be a lot easier to use and understand exactly what it does.

**Comment by ltdrdata** [comment]
> Thanks for your answer @Kaharos94, however I'm not positive it's fully answers what I asked. For example, it's still unclear how does it get to the upscaled image size.
> 
> On that example I posted it scaled an area of 622 x 657 (in other words, already bigger than 256) up ~1.2 times, to 704 x 768, which mostly just changes the image without actually improving it in any way. Why didn't it simply upscale to something bigger (but still multiple of 64) like 1024 x 1280, which would be more like a 2x upscale that would really improve the image? How can I determine a value that would improve my rendering quality without having to test each image first? More important, how does it get from that value of `256` to the size of 704 x 768 it choose? That's the part that puzzles me.
> 
> I guess my issue is that this one variable doesn't provide enough context to really determine what a good value would be without knowing already what the result is, which undercuts the goal of the tool in the first place. 
> 
> Wouldn't it be more useful to have a property that lets me determine the maximum image size I'm interested in rendering, and perhaps the desired scaling ratio (or maximum and minimum ratios), which together could be used to determine the rendering size without any guess work? So if I select a maximum render size of 1280px, maximum ratio of 4x and minimum of 2x, then the plugin could use these numbers to find the biggest (for best quality) image size that fits in that range of scaling ratios. If the smallest 2x scaling is bigger than 1280, it skips because the detected area is too big.
> 
> It would be a lot easier to use and understand exactly what it does.

When I first started creating the Impact Pack, my goal was to implement a more generalized version of the ddetailer extension in the comfyui style within the webui.

The reason why facial details can be lost is when generating images at too small a resolution. Therefore, providing a resolution that is large enough for the user to be satisfied can handle this issue.

The bbox detector for facial detection detects a rectangular range limited to the face. However, if regeneration is restricted to this narrow range, there is an issue where the context is lost, resulting in improper facial generation. The crop_factor cuts out an area several times larger than the bbox to provide sufficient context for regeneration.

Determining the resolution based on the cropped area is not appropriate for preserving facial details. Therefore, a guide_size is given based on the bbox to ensure that the facial area is regenerated at a minimum size of 512. However, if the face is already 512 in size, it has sufficient detail, and there is no need to regenerate it for additional details. In this case, it is skipped.

To be more precise, the upscale of the bbox ensures that it is a multiple of 64, and that the smallest side is larger than or equal to the guide_size.

This approach is particularly useful when multiple faces of different sizes are detected in a single image.

Applying guide_size based on crop_size is an extension that was developed for more general use cases beyond just faces. The scaling and skipping conditions are the same as with bbox, but the reference point is crop_size. This approach helps prevent unexpected scaling factors from becoming too large.

Recently, we have been considering expanding the option to always recreate with an upscale factor of 1 even if there is no upscaling, in order to assist simple inpainting tasks through mask painting and segmentation.

I will consider reflecting your opinion after review.
