### ISSUE TITLE
When using Face Detector, the face is brightened.

### ISSUE THREAD

**Issue by Neytiri7** [ltdrdata/ComfyUI-Impact-Pack#621]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139053327/6bda684b-73bc-4ab7-8978-7a063d30021b)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139053327/a898c519-bfe3-4236-abf8-e605c546eb0d)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139053327/7650de00-c2e8-4f40-b327-9fe82153c49d)

If you use Face Detector for Face Detector, the face image will be too white.

I've tried changing to a prompt, and changing the numerical value (denoise) of each item, but it's output brightly.

It's hard to check the area other than the face,
Only the face is displayed particularly brightly.

It also appears bright on the MediaPipeFaceMesh Detector Provider node, 
The Ultralytics Detector Provider node is bright in Face Detector, both bbox and segm. 

Which item controls the brightness of your face?
Please check if it is deformed while processing it in the Detailer.

**Comment by ltdrdata** [comment]
First, it's important to clarify that the Detector only detects and does not alter the image. It seems you are confusing the Detector with the Detailer.

There are two main aspects to consider regarding changes in the color of the face:

1. The Detector crops the detected area, and the Detailer performs inpainting on the cropped area. If the cropped area is too narrow, it can create a mismatch because it lacks the context of the surrounding area (outside of  cropped area).

This can be addressed by increasing the `crop_factor`, allowing the inpainting process to use a broader range of information. However, if the `crop_factor` is set too high, it might essentially target the entire image area. This can become problematic when dealing with high resolution.

2. The conditioning you supplied to the Detailer might be causing the face to appear brighter.

To fix this, you should adjust the prompt appropriately or use different conditioning methods, such as ipadapter.

**Comment by Neytiri7** [comment]
I already know the difference between 'Detector' and 'Detailer' very well, so I uploaded the issue.

The issue was being reproduced only in the face-related Detector, and we found that this could not be solved only by the placement of nodes or the setting of numbers.

As you said, if it's a 'crop_factor' problem,
It should come from the same size as the face, hands, feet, the same setting, nothing written at the prompt, but it wasn't. It was expressed exceptionally brightly only on the face.

As a former 'QA', I conducted tests in a workflow that rearranged various models and sequences, but it was the same as coming out of the face.

However, we only found out that the brightness intensity varies depending on the workflow order.

In the initial generated image, if you do 'Upscale', 'Hires', and then the 'Detailer' proceeds, the face is bright enough to be expressed white,
In the initial generated image, if you go straight through the Detailer, the face is brightened, but not so white.

I was wondering if it was a technical problem, but you said it was a problem with crop_factor numerical control, and it wasn't a technical problem...
We need to change the crop_factor number and test whether it can be reproduced.

Thank you.
