### ISSUE TITLE
wildcard processors don't work with primitive string inputs

### ISSUE THREAD

**Issue by monkeyguy** [ltdrdata/ComfyUI-Impact-Pack#63]
this pic shows how the primitive-connected processor didn't populate, but the widget input processor did, same holds true for output

is there a node that wildcard processors _can_ accept a string input from?

![Screenshot 2023-07-31 220619](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/37457606/eb2fbc78-2c11-4ce8-ad28-dbd463acd7b5)

**Comment by ltdrdata** [comment]
The issue is originally a limitation of the ImpactWildcardProcessor. However, we are planning to improve it as it is beneficial and not difficult to enhance when associated with Primitives.

However, even with the improvements, we still cannot guarantee its effectiveness for connections other than Primitive nodes. This is a mechanism to determine prompts when prompt is passed into ComfyUI's internals from the browser.

**Comment by ltdrdata** [comment]
Patched this in V3.6

https://www.youtube.com/watch?v=zQa0nJO7gxI

**Comment by monkeyguy** [comment]
thank you!

**Comment by monkeyguy** [comment]
thank you!
