### ISSUE TITLE
How to combine multiple segs

### ISSUE THREAD

**Issue by gzxg1234** [ltdrdata/ComfyUI-Impact-Pack#67]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/14349698/072acda1-1c70-402f-9b08-8658c3d8b4f6)

I have a face detector and hand detector, i want to combine them and output to SAMDetector

**Comment by ltdrdata** [comment]
There is currently no SEGS concat node. I am considering adding it since it could be beneficial. 

However, separate from this, sending hand recognition to SAM should be approached with caution.
When recognized by SAM, it selects based on the center of the mask, which can lead to inaccuracies due to complex shapes like hands, potentially causing incorrect mask selection as the hand extends beyond the mask's boundaries.

If the intention is not just to enhance the surface of the hand in its correct form, but also to rectify an incorrect hand, it is useful to widen the scope of the mask area to allow for potential alterations to the hand's shape.

**Comment by ltdrdata** [comment]
I implemented this in V3.6.
Now you can see `ImpactSEGSConcat` (a.k.a `SEGS Concat`)
