### ISSUE TITLE
[REQUEST] Option to get a different wildcard value for each object when using batch_size

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [ltdrdata/ComfyUI-Impact-Pack#679]
I'm trying to generate multiple images at the same time using `batch_size` in comfy, and I want each "batched" image to use a different seed for the wildcard processor.

But I seem to be unable to get a new random selection from my wildcard, even if I am trying to use the KSampler (inspire) and batch_seed_mode to be incremental. 

Is this possible? I want it to behave like A1111, where each batched image gets different values from the wildcards.

![image](https://github.com/user-attachments/assets/ddc767f3-e72d-4ee5-b4c7-93be6d19d7f9)

**Comment by ltdrdata** [comment]
Due to the structure of KSampler, it's not possible to apply wildcards in batch. Wildcards are determined at the string level, and by the time they are passed to KSampler, they have already been encoded as CONDITIONING.

Moreover, if it's set to change the LoRA applied in the wildcard, the model passed to KSampler will also change. I'm not sure how A1111's wildcard processing method is internally structured, but in cases where the model changes, it cannot be processed in batch mode.

What you want should be implemented in the form of a list, not a batch.

![wildcard-list2](https://github.com/user-attachments/assets/824b3589-4a32-44ba-9a99-39bf98c11f5d)

NOTE: mode should be `fixed` and wildcard  text should be written in `populated_text`.
