### ISSUE TITLE
A suggestion, is it possible to implement

### ISSUE THREAD

**Issue by BoosterCore** [ltdrdata/ComfyUI-Impact-Pack#687]
Is it possible to modify the code so that I can customize the model path , such as SAMS, in the `extra_model_paths.yaml` document?
I think this will allow multiple copies of ComfyUI to share models, avoiding repeated downloads of models and taking up a lot of disk space.
In addition, with more and more plugins nowadays, various dependency conflicts are also very frequent, so it is very necessary to use multiple copies of Comfy UI.

Maybe you can refer to this：
https://github.com/GreenLandisaLie/AuraSR-ComfyUI/issues/10

**Comment by ltdrdata** [comment]
You can use "sams" already.

**Comment by BoosterCore** [comment]
I tried, but it not work
![image](https://github.com/user-attachments/assets/f915cde8-56f7-4ecd-9672-083196a58d42)

**Comment by ltdrdata** [comment]
I have no problem.
I'm not sure if it's because of your font issue that the `_` is not visible, or if it's really base path instead of `base_path`.

1. Make sure `base_path` instead of `base path`.
2. If you're still experiencing problems, try disabling all custom nodes except for the impact pack and test it. Always remember to refresh your browser when you restart

**Comment by BoosterCore** [comment]
Regardless of the outcome, I would like to express my sincere gratitude for your patience in answering. 
I'm not quite sure why this issue is occurring on my end, as it doesn't seem to be font-related and there are no missing underscores. 
It's rather strange that some directories can function normally while others cannot. 
I will continue trying and thank you again.

**Comment by BoosterCore** [comment]
Finally, I use `mklink `to solve this issue
