### ISSUE TITLE
Nodes from examples are not exist in your extension

### ISSUE THREAD

**Issue by ssbugman** [ltdrdata/ComfyUI-Impact-Pack#691]
There no node named "MMDetDetectorProvider" in your extension. Is you extension incompatible with extensions manager and strictly require manual setup?

After manual setup this node still not exist. You need provide dependencies info or your custom nodes useless without them.

**Comment by ltdrdata** [comment]
The MMDetDetector-related Node has been maintained for a while for existing users, but it is ultimately a node that will be removed. Use the Ultralytics Node instead.

MMDet-related dependencies have been discontinued long ago due to unresolvable issues in various environments.

https://github.com/ltdrdata/ComfyUI-Impact-Pack?tab=readme-ov-file#mmdet-nodes-deprecated---dont-use-these-nodes
