### ISSUE TITLE
Update PermissionError

### ISSUE THREAD

**Issue by bluenyx** [ltdrdata/ComfyUI-Impact-Pack#864]
Do I have to run it as an administrator?
The update failed in the Manager, so it's the same even if it's manually.

![image](https://github.com/user-attachments/assets/7e39dc59-f58f-432f-9045-3c714af53ae4)

**Comment by ltdrdata** [comment]
1. This issue occurs because Windows does not properly support overly long paths.  
There are two options:  
One option is to move the ComfyUI installation directly under `C:\`  
The other option is to edit the registry to enable support for longer paths.

https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

2. The version of `Impact Pack` you are installing is outdated.  
`Impact Pack` and `Impact Subpack` have been separated.  

It is recommended to remove `ComfyUI-Impact-Pack` and install the latest versions of `ComfyUI-Impact-Pack` and `ComfyUI-Impact-Subpack`.
