### ISSUE TITLE
Execution Nodes

### ISSUE THREAD

**Issue by sedetweiler** [ltdrdata/ComfyUI-Impact-Pack#93]
Can you explain the use of the execution nodes, please?  I see them in many of the components, but would like to know their actual function.

**Comment by ltdrdata** [comment]
> Can you explain the use of the execution nodes, please?  I see them in many of the components, but would like to know their actual function.

Do you meaning ExecutionOneOf, ExecutionSwitch, ...?

They are not belongs to Impact Pack.
You can use it only inside of the component.

It's very experimental nodes. So you have to use it carefully. 

Execution... series is used for control execution path.

For example, execution switch passthru only selected path and block all other path.

And ExecutionOneOf passthru only one of reached input.

So you can execute specific workflow part instead of full workflow through this.

But these mechanism cannot work in normal workflow executor. And I'll change the mechanism soon.
That is the reason why I didn't registered workflow component extension into ComfyUI Mananger.

I don't want to spreading of unreliable workflow everywhere.

**Comment by sedetweiler** [comment]
Sounds good. I just noticed they were used in a few of the workflows and
wanted to understand them better.
